[target.avr-unknown-gnu-attiny25]
rustflags = ["-C", "link-arg=-Tlink.ld"]

[build]
target = ["avr-attiny25.json"]
#target = ["avr-unknown-gnu-attiny25"]
#rustflags = ["-Z build-std=core --target avr-atmega328p.json --release"]
#TODO should usually be done via target.<tripple>.rustflags and target.<cfg>.rustflags

[unstable]
unstable-options = true
build-std = ["core"]

[env]
AVR_CPU_FREQUENCY_HZ="4000000"

#[target.avr-unknown-gnu-attiny25]
[target.'cfg(all(target_arch = "avr"))']
linker="avr-gcc"
#linker="C:\\Users\\User\\CLionProjects\\Rust\\avr8-gnu-toolchain-win32_x86_64\\bin\\avr-gcc.exe"